"use client"
import '../public/globals.css'
import { FooterComponents } from './-Componets/footer/footerComponents'
import { HeaderComponents } from './-Componets/header/headerComponents'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { useGet } from './-Hooks/useGet.hooks'
import { AppProvider } from './-Context/app.context'

const inter = Inter( { subsets: ['latin'] } )

export const metadata: Metadata = {
  title: 'Avo Store',
  description: 'Generated by create next app',
}

export default function RootLayout( {
  children
}: {
  children: React.ReactNode
} ) {
  return (
    <html lang="en">
      <body className="">
        <AppProvider>
          <HeaderComponents />
          {children}
          <FooterComponents />
        </AppProvider>
      </body>
    </html>
  )
}
